ONE_HOUR_THRESHOLD   = 300
ONE_DAY_THRESHOLD    = 300
THREE_DAYS_THRESHOLD = 300
MIN_VALUES_PER_DAY   = 200
# ex: ['gt-evnsense-030', 'gt-envsense-025']
ONE_HOUR_IGNORE      = []
ONE_DAY_IGNORE       = []
THREE_DAY_IGNORE     = []
MIN_VALUES_IGNORE    = []
